# Simple Docker Compose for Personal LaCentrale Scraper
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: lacentrale_postgres
    environment:
      POSTGRES_DB: lacentrale_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password_here}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lacentrale_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PgAdmin (Database Web Interface - Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lacentrale_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@lacentrale.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - tools  # Optional service

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
