# Simple Docker Compose for LaCentrale Scraper Tools
# Uses your existing PostgreSQL database (no new database created)
version: '3.8'

services:
  # PgAdmin (Database Web Interface - connects to your existing database)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lacentrale_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@lacentrale.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    network_mode: "host"  # Access your local PostgreSQL database

  # Selenium Chrome (Optional - for debugging browser issues)
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: lacentrale_chrome
    environment:
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_PASSWORD=secret
    ports:
      - "4444:4444"  # Selenium Grid
      - "7900:7900"  # VNC Server for debugging
    shm_size: 2gb
    restart: unless-stopped
    profiles:
      - debug  # Only start when debugging

volumes:
  pgadmin_data:
    driver: local